In [65]:
import pandas as pd 

df = pd.read_csv('/Users/zentrovoy/Documents/BOOTCAMP/TEST/loan.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [66]:

df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [67]:
df.isnull().sum() / len(df) * 100

Loan_ID              0.000000
Gender               2.117264
Married              0.488599
Dependents           2.442997
Education            0.000000
Self_Employed        5.211726
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           3.583062
Loan_Amount_Term     2.280130
Credit_History       8.143322
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [68]:
df = df.dropna(subset=['Gender','Married','Dependents','Self_Employed'])
df.drop('Loan_ID', axis=1, inplace=True)

In [69]:
# df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].median())

# df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median(), inplace=True)
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median())

# df['Credit_History'].fillna(df['Credit_History'].mode()[0], inplace=True)
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].median())

In [70]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,127.0,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [71]:
df['Gender'] = df['Gender'].map({'Male':1,'Female':0})
df['Married'] = df['Married'].map({'Yes':1,'No':0})
df['Education'] = df['Education'].map({'Graduate':1, 'Not Graduate':0})
df['Self_Employed'] = df['Self_Employed'].map({'Yes':1,'No':0})
df['Loan_Status'] = df['Loan_Status'].map({'Y':1,'N':0})

In [72]:
df = pd.get_dummies(df, columns=['Property_Area'])
df = pd.get_dummies(df, columns=['Dependents'])

In [73]:
df

,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Dependents_0,Dependents_1,Dependents_2,Dependents_3+
0,1,0,1,0,5849,0.0,127.0,360.0,1.0,1,False,False,True,True,False,False,False
1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,True,False,False,False,True,False,False
2,1,1,1,1,3000,0.0,66.0,360.0,1.0,1,False,False,True,True,False,False,False
3,1,1,0,0,2583,2358.0,120.0,360.0,1.0,1,False,False,True,True,False,False,False
4,1,0,1,0,6000,0.0,141.0,360.0,1.0,1,False,False,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,1,0,2900,0.0,71.0,360.0,1.0,1,True,False,False,True,False,False,False
610,1,1,1,0,4106,0.0,40.0,180.0,1.0,1,True,False,False,False,False,False,True
611,1,1,1,0,8072,240.0,253.0,360.0,1.0,1,False,False,True,False,True,False,False
612,1,1,1,0,7583,0.0,187.0,360.0,1.0,1,False,False,True,False,False,True,False
613,0,0,1,1,4583,0.0,133.0,360.0,0.0,0,False,True,False,True,False,False,False

In [74]:
X = df.drop('Loan_Status', axis=1)
y = df['Loan_Status']

In [75]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42, stratify=y)

In [76]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [77]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8203592814371258
              precision    recall  f1-score   support

           0       0.89      0.48      0.62        52
           1       0.81      0.97      0.88       115

    accuracy                           0.82       167
   macro avg       0.85      0.73      0.75       167
weighted avg       0.83      0.82      0.80       167

In [80]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(class_weight='balanced', random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8083832335329342
              precision    recall  f1-score   support

           0       0.78      0.54      0.64        52
           1       0.82      0.93      0.87       115

    accuracy                           0.81       167
   macro avg       0.80      0.73      0.75       167
weighted avg       0.80      0.81      0.80       167